Update OOOq & get ready for OSP15/Stein
Change-Id: If38d3d170a6c20ec955de07541443004b99c3370

diff --git a/roles/collect-logs/tasks/collect.yml b/roles/collect-logs/tasks/collect.yml
--- a/roles/collect-logs/tasks/collect.yml
+++ b/roles/collect-logs/tasks/collect.yml
@@ -3,12 +3,13 @@
   ignore_errors: true
   block:
     - name: Ensure required rpms for logging are installed
-      yum:
+      package:
+        state: present
         name:
           - gzip
           - rsync
+          - socat
           - tar
-        state: present
 
     - name: Prepare directory with extra logs
       file: dest=/var/log/extra state=directory
@@ -16,11 +17,24 @@
     - name: rpm -qa
       shell: rpm -qa | sort -f >/var/log/extra/rpm-list.txt
 
-    - name: yum list installed
-      shell: yum list installed >/var/log/extra/yum-list-installed.txt
+    - name: package list installed
+      shell: "{{ ansible_pkg_mgr }} list installed >/var/log/extra/package-list-installed.txt"
 
-    - name: Collecting cpu information
-      shell: cat /proc/cpuinfo &> /var/log/extra/cpuinfo.txt
+    - name: list enabled repositories
+      shell: "{{ ansible_pkg_mgr }} repolist -v >/var/log/extra/repolist.txt"
+
+    - name: Collecting /proc/cpuinfo|meminfo|swaps
+      shell: "cat /proc/{{ item }} &> /var/log/extra/{{ item }}.txt"
+      with_items:
+        - cpuinfo
+        - meminfo
+        - swaps
+
+    - name: Collect installed cron jobs
+      shell: |
+        for user in $(cut -f1 -d':' /etc/passwd); do \
+        echo $user; crontab -u $user -l | grep -v '^$\|^\s*\#\|^\s*PATH'; done \
+        &> /var/log/extra/installed_crons.txt
 
     # used by OSP Release Engineering to import into internal builds
     - name: package import delorean
@@ -31,31 +45,47 @@
     # used by OSP Release Engineering to import into internal builds
     - name: package import delorean-testing
       shell: |
-        repoquery --disablerepo='*' --enablerepo='delorean-*-testing'\
-        -a --qf '%{sourcerpm}'|sort -u|sed 's/.src.rpm//g' >> /var/log/extra/import-delorean-testing.txt
+        repoquery --disablerepo='*' --enablerepo='delorean-*-deps'\
+        -a --qf '%{sourcerpm}'|sort -u|sed 's/.src.rpm//g' >> /var/log/extra/import-delorean-deps.txt
 
     - name: Collect logs from all failed systemd services
       shell: >
         systemctl -t service --failed --no-legend | awk '{print $1}'
-        | xargs -r -n1 journalctl -u > /var/log/extra/services.txt 2>&1
+        | xargs -r -n1 journalctl -u > /var/log/extra/failed_services.txt 2>&1
 
     - name: Collect network status info
       shell: >
-        (ip a; ip r; iptables-save; iptables -nL) &> /var/log/extra/network.txt;
+        echo "netstat" > /var/log/extra/network.txt;
+        netstat -i &> /var/log/extra/network.txt;
+        for ipv in 4 6; do
+          echo "### IPv${ipv} addresses" >> /var/log/extra/network.txt;
+          ip -${ipv} a &>> /var/log/extra/network.txt;
+          echo "### IPv${ipv} routing" >> /var/log/extra/network.txt;
+          ip -${ipv} r &>> /var/log/extra/network.txt;
+          echo "### IPTables (IPv${ipv})" &>> /var/log/extra/network.txt;
+          test $ipv -eq 4 && iptables-save &>> /var/log/extra/network.txt;
+          test $ipv -eq 6 && ip6tables-save &>> /var/log/extra/network.txt;
+        done;
         (for NS in $(ip netns list); do
-        echo "==== $NS ====";
-        ip netns exec $NS ip a;
-        ip netns exec $NS ip r;
-        ip netns exec $NS ip iptables-save;
-        PIDS="$(ip netns pids $NS)";
-        [[ ! -z "$PIDS" ]] && ps --no-headers -f --pids "$PIDS";
-        echo "";
-        done) &> /var/log/extra/network-netns;
+          for ipv in 4 6; do
+            echo "==== $NS (${ipv})====";
+            echo "### IPv${ipv} addresses";
+            ip netns exec $NS ip -${ipv} a;
+            echo "### IPv${ipv} routing";
+            ip netns exec $NS ip -${ipv} r;
+            echo "### IPTables (IPv${ipv})";
+            test $ipv -eq 4 && ip netns exec $NS ip iptables-save;
+            test $ipv -eq 6 && ip netns exec $NS ip ip6tables-save;
+          done
+          PIDS="$(ip netns pids $NS)";
+          [[ ! -z "$PIDS" ]] && ps --no-headers -f --pids "$PIDS";
+          echo "";
+        done) &>> /var/log/extra/network-netns;
         (for NB in $(ovs-vsctl show | grep Bridge |awk '{print $2}'); do
-        echo "==== Bridge name - $NB ====";
-        ovs-ofctl show $NB;
-        ovs-ofctl dump-flows $NB;
-        echo "";
+          echo "==== Bridge name - $NB ====";
+          ovs-ofctl show $NB;
+          ovs-ofctl dump-flows $NB;
+          echo "";
         done;
         ovsdb-client dump) &> /var/log/extra/network-bridges;
 
@@ -82,6 +112,13 @@
         nova list &> /var/log/extra/nova_list.txt;
         fi
 
+    - name: Get haproxy stats
+      shell: >
+        pgrep haproxy && \
+        test -S /var/lib/haproxy/stats && \
+        echo 'show info;show stat;show table' | socat /var/lib/haproxy/stats stdio &> /var/log/extra/haproxy-stats.txt || \
+        echo "No HAProxy or no socket on host" > /var/log/extra/haproxy-stats.txt
+
     - name: lsmod
       shell: "lsmod &> /var/log/extra/lsmod.txt"
 
@@ -94,12 +131,55 @@
     - name: lvm debug
       shell: "(vgs; pvs; lvs) &> /var/log/extra/lvm.txt"
 
+    - name: Collect services status
+      shell: |
+        systemctl list-units --full --all &> /var/log/extra/services.txt
+        systemctl status "*" &>> /var/log/extra/services.txt
+
+    - name: check if ODL is enabled via docker
+      shell: docker ps | grep opendaylight_api
+      register: odl_container_enabled
+
+    - name: check if ODL is enabled via podman
+      shell: podman ps | grep opendaylight_api
+      register: odl_container_enabled
+      when: odl_container_enabled.rc != 0
+
+
+    - name: check if ODL is enabled via rpm
+      shell: rpm -qa | grep opendaylight
+      register: odl_rpm_enabled
+
+    - name: Create ODL log directory
+      file: dest="{{ odl_extra_log_dir }}" state=directory
+      when: (odl_rpm_enabled.rc == 0) or (odl_container_enabled.rc == 0)
+
+    - name: Create rsync filter file
+      template:
+        src: "odl_extra_logs.j2"
+        dest: "/tmp/odl_extra_logs.sh"
+
+    - name: Collect OVS outputs for ODL
+      shell: "bash /tmp/odl_extra_logs.sh"
+      when: (odl_rpm_enabled.rc == 0) or (odl_container_enabled.rc == 0)
+
+    - name: Collect ODL info and logs (RPM deployment)
+      shell: >
+        cp /opt/opendaylight/data/log/* /var/log/extra/odl/;
+        journalctl -u opendaylight > /var/log/extra/odl/odl_journal.log
+      when: odl_rpm_enabled.rc == 0
+
     - name: Generate human-readable SAR logs
       shell: "[[ -f /usr/lib64/sa/sa2 ]] && /usr/lib64/sa/sa2 -A"
 
     - name: check for dstat log file
       stat: path=/var/log/extra/dstat-csv.log
       register: dstat_logfile
+
+    - name: kill dstat
+      shell: "pkill dstat"
+      become: true
+      when: dstat_logfile.stat.exists
 
     - name: Get dstat_graph tool
       git:
@@ -130,7 +210,9 @@
         grep -v ansible-command /var/log/messages | grep oom-killer > /var/log/extra/oom-killers.txt
 
     - name: Ensure sos package is installed when collect sosreport(s)
-      yum: name=sos state=present
+      package:
+        name: sos
+        state: present
       when: artcl_collect_sosreport|bool
 
     - name: Collect sosreport
@@ -149,38 +231,107 @@
         mv /tmp/delorean_logs/home/{{ undercloud_user }}/DLRN/data/repos/* {{ artcl_collect_dir }}/delorean_logs/;
         fi
 
-    - name: Collect docker info and logs
+    - name: Collect container info and logs
       shell: >
-        if command -v docker && systemctl is-active docker; then
-            BASE_DOCKER_EXTRA=/var/log/extra/docker;
-            mkdir -p $BASE_DOCKER_EXTRA;
-            All_FILE=$BASE_DOCKER_EXTRA/docker_allinfo.log;
-            docker ps --all --size &> $All_FILE;
-            docker images &>> $All_FILE;
-            docker volume ls &>> $All_FILE;
-            docker stats --all --no-stream &>> $All_FILE;
-            docker info &>> $All_FILE;
-            for cont in $(docker ps | awk {'print $NF'} | grep -v NAMES); do
-                INFO_DIR=$BASE_DOCKER_EXTRA/containers/${cont};
-                mkdir -p $INFO_DIR;
-                INFO_FILE=$INFO_DIR/docker_info.log;
-                echo "+ docker top $cont auxw" > $INFO_FILE;
-                docker top $cont auxw &>> $INFO_FILE;
-                echo "+ docker exec $cont top -bwn1" >> $INFO_FILE;
-                docker exec $cont top -bwn1 &>> $INFO_FILE;
-                echo "+ docker inspect $cont" >> $INFO_FILE;
-                docker inspect $cont &>> $INFO_FILE;
-                docker logs $cont &> $INFO_DIR/stdout.log;
-                docker cp $cont:/var/lib/kolla/config_files/config.json $INFO_DIR/config.json;
-                # NOTE(flaper87): This should go away. Services should be
-                # using a `logs` volume
-                docker cp $cont:/var/log $INFO_DIR/log;
+        for engine in docker podman; do
+
+            if [ $engine = 'docker' ]; then
+                (command -v docker && systemctl is-active docker) || continue
+                # container_cp CONTAINER SRC DEST
+                container_cp() {
+                  docker cp ${1}:${2} $3
+                }
+                # NOTE(ykarel) podman inspect returns 'source' while docker inspect returns 'Source'
+                source_mount=Source
+            fi
+
+            if [ $engine = 'podman' ]; then
+                command -v podman || continue
+                # NOTE(cjeanner): podman has no "cp" subcommand, we hence have to mount the container, copy,
+                # umount it. More info: https://www.mankier.com/1/podman-cp
+                # See also: https://github.com/containers/libpod/issues/613
+                container_cp() {
+                  mnt=$(podman mount $1)
+                  cp -rT ${mnt}${2} $3
+                  podman umount $1
+                }
+                # NOTE(ykarel) podman inspect returns 'source' while docker inspect returns 'Source'
+                source_mount=source
+            fi
+
+            BASE_CONTAINER_EXTRA=/var/log/extra/${engine};
+            mkdir -p $BASE_CONTAINER_EXTRA;
+            ALL_FILE=$BASE_CONTAINER_EXTRA/${engine}_allinfo.log;
+
+            CONTAINER_INFO_CMDS=(
+                "${engine} ps --all --size"
+                "${engine} images"
+                "${engine} stats --all --no-stream"
+                "${engine} version"
+                "${engine} info"
+            );
+            if [ $engine = 'docker' ]; then
+                CONTAINER_INFO_CMDS+=("${engine} volume ls")
+            fi
+            for cmd in "${CONTAINER_INFO_CMDS[@]}"; do
+                echo "+ $cmd" >> $ALL_FILE;
+                $cmd >> $ALL_FILE;
+                echo "" >> $ALL_FILE;
+                echo "" >> $ALL_FILE;
             done;
 
-            # NOTE(flaper87) Copy contents from the logs volume. We can expect this
-            # volume to exist in a containerized environment.
-            cp -r /var/lib/docker/volumes/logs/_data $BASE_DOCKER_EXTRA/logs;
-        fi
+            # Get only failed containers, in a dedicated file
+            ${engine} ps -a | grep -vE ' (IMAGE|Exited \(0\)|Up) ' &>> /var/log/extra/failed_containers.log;
+
+            for cont in $(${engine} ps | awk {'print $NF'} | grep -v NAMES); do
+                INFO_DIR=$BASE_CONTAINER_EXTRA/containers/${cont};
+                mkdir -p $INFO_DIR;
+                (
+                  set -x;
+                  if [ $engine = 'docker' ]; then
+                      ${engine} top $cont auxw;
+                  # NOTE(cjeanner): `podman top` does not support `ps` options.
+                  elif [ $engine = 'podman' ]; then
+                      ${engine} top $cont;
+                  fi
+                  ${engine} exec $cont top -bwn1;
+                  ${engine} exec $cont bash -c "\$(command -v dnf || command -v yum) list installed";
+                  ${engine} inspect $cont;
+                ) &> $INFO_DIR/${engine}_info.log;
+
+                container_cp $cont /var/lib/kolla/config_files/config.json $INFO_DIR/config.json;
+
+                # NOTE(flaper87): This should go away. Services should be
+                # using a `logs` volume
+                # NOTE(mandre) Do not copy logs if the containers is bind mounting /var/log directory
+                if ! ${engine} inspect $cont | jq .[0].Mounts[].$source_mount | grep -x  '"/var/log[/]*"' 2>1 > /dev/null; then
+                      container_cp $cont /var/log $INFO_DIR/log;
+                fi;
+
+                # Delete symlinks because they break log collection and are generally
+                # not useful
+                find $INFO_DIR -type l -delete;
+            done;
+
+            # NOTE(cjeanner) previous loop cannot have the "-a" flag because of the
+            # "exec" calls. So we just loop a second time, over ALL containers,
+            # in order to get all the logs we can. For instance, the previous loop
+            # would not allow to know why a container is "Exited (1)", preventing
+            # efficient debugging.
+            for cont in $(${engine} ps -a | awk {'print $NF'} | grep -v NAMES); do
+                INFO_DIR=$BASE_CONTAINER_EXTRA/containers/${cont};
+                mkdir -p $INFO_DIR;
+                ${engine} logs $cont &> $INFO_DIR/stdout.log;
+            done;
+
+          # NOTE(flaper87) Copy contents from the logs volume. We can expect this
+          # volume to exist in a containerized environment.
+          # NOTE(cjeanner): Rather test the eXistenZ of the volume, as podman does not
+          # have such thing
+          if [ -d /var/lib/docker/volumes/logs/_data ]; then
+              cp -r /var/lib/docker/volumes/logs/_data $BASE_CONTAINER_EXTRA/logs;
+          fi
+        done
 
     - name: Collect config-data
       shell: cp -r /var/lib/config-data/puppet-generated /var/log/config-data
@@ -188,11 +339,16 @@
     - name: Collect text version of the journal from last four hours
       shell: journalctl --since=-4h --lines=100000 > /var/log/journal.txt
 
-    - name: Collect errors
+    - name: Collect errors and rename if more than 10 MB
       shell: >
         grep -rE '^[-0-9]+ [0-9:\.]+ [0-9 ]*ERROR ' /var/log/ |
         sed "s/\(.*\)\(20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]\.[0-9]\+\)\(.*\)/\2 ERROR \1\3/g" > /tmp/errors.txt;
-        mv /tmp/errors.txt /var/log/extra/errors.txt
+        if (( $(stat -c "%s" /tmp/errors.txt) > 10485760 )); then
+          ERR_NAME=big-errors.txt;
+        else
+          ERR_NAME=errors.txt;
+        fi;
+        mv /tmp/errors.txt /var/log/extra/${ERR_NAME}.txt
 
     - name: Create a index file for logstash
       shell: >
@@ -200,31 +356,9 @@
         cat $i; done | grep "^20.*|" | sort -sk1,2 |
         sed "s/\(20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]\.*[0-9]*\)\(.*\)/\1 INFO \2/g" > /var/log/extra/logstash.txt
 
-    # Collect host info as done presently in TripleO-CI.
-    # Will be deprecated.
-    - name: Create get_host_info script
-      template:
-        src: "get_host_info.sh.j2"
-        dest: "/tmp/get_host_info.sh"
-        mode: 0755
-
-    - name: Copy heat-deploy-times.py to host
-      copy:
-        src: heat-deploy-times.py
-        dest: "/tmp/heat-deploy-times.py"
-        mode: 0755
-
-    - name: Call get_host_info script
-      shell: /tmp/get_host_info.sh &>/var/log/host_info.txt
-
-    - name: Erase temporary log directory if exists
-      file:
-        path: "/tmp/{{ inventory_hostname }}"
-        state: absent
-
 - name: Set default collect list
   set_fact:
-    collect_list: "{{ artcl_collect_list }}"
+    collect_list: "{{ artcl_collect_list }} + {{ artcl_collect_list_append|default([]) }}"
 
 - name: Override collect list
   set_fact:
@@ -244,8 +378,9 @@
     dest: "/tmp/{{ inventory_hostname }}-rsync-filter"
 
 - name: Gather the logs to /tmp
-  become: yes
+  become: true
   shell: >
+    set -o pipefail &&
     rsync --quiet --recursive --copy-links --prune-empty-dirs
     --filter '. /tmp/{{ inventory_hostname }}-rsync-filter' / /tmp/{{ inventory_hostname }};
     find /tmp/{{ inventory_hostname }} -type d -print0 | xargs -0 chmod 755;
@@ -270,16 +405,16 @@
   fetch:
     src: "/tmp/{{ inventory_hostname }}.tar.gz"
     dest: "{{ artcl_collect_dir }}/{{ inventory_hostname }}.tar.gz"
-    flat: yes
-    validate_checksum: no
+    flat: true
+    validate_checksum: false
   when: artcl_tar_gz|bool
 
 - name: Fetch log archive (tar)
   fetch:
     src: "/tmp/{{ inventory_hostname }}.tar"
     dest: "{{ artcl_collect_dir }}/{{ inventory_hostname }}.tar"
-    flat: yes
-    validate_checksum: no
+    flat: true
+    validate_checksum: false
   when: artcl_gzip_only|bool
 
 - name: Delete temporary log directory after collection
