Update roles
Change-Id: I87f697047e598b109b120498f2cf2cc01b929632

diff --git a/roles/train/tripleo-validations/templates/run-tripleo-validations.sh.j2 b/roles/train/tripleo-validations/templates/run-tripleo-validations.sh.j2
--- a/roles/train/tripleo-validations/templates/run-tripleo-validations.sh.j2
+++ b/roles/train/tripleo-validations/templates/run-tripleo-validations.sh.j2
@@ -25,6 +25,8 @@ fi
 ## * Getting the list of validations belonging to the group.
 ## ::
 
+{% if release <= "stein" %}
+
 LIST_VALIDATIONS=$(openstack action execution \
         run tripleo.validations.list_validations \
         "{\"groups\": [\"$GROUP_NAME\"]}" | jq ".result[] | .id" | tr -d '"')
@@ -63,5 +65,27 @@ for validation_name in $LIST_VALIDATIONS; do
         fi
 done
 
-## --stop_docs
+{% else %}
 
+LIST_VALIDATIONS=$(openstack tripleo validator list -c ID --format value --group "${GROUP_NAME}")
+
+## * Run validations tests one by one defined in the group.
+## ::
+
+if [ -f "{{ failed_validations_log }}" ]; then
+    rm -Rf "{{ failed_validations_log }}"
+fi
+
+for validation_name in $LIST_VALIDATIONS; do
+    set +e
+    OUTPUT=$(timeout --kill-after=10s {{ validations_max_retries }}s openstack tripleo validator run --validation "${validation_name}" 2>&1)
+    if [ $? -ne 0 ]; then
+        echo "### ${validation_name} FAILED" | tee -a {{ failed_validations_log }}
+    fi
+    set -e
+    echo ${OUTPUT} | tee -a {{ failed_validations_log }}
+done
+
+{% endif %}
+
+## --stop_docs
