Update OOOq & get ready for OSP15/Stein
Change-Id: If38d3d170a6c20ec955de07541443004b99c3370

diff --git a/roles/collect-logs/templates/get_host_info.sh.j2 b/roles/collect-logs/templates/get_host_info.sh.j2
--- a/roles/collect-logs/templates/get_host_info.sh.j2
+++ b/roles/collect-logs/templates/get_host_info.sh.j2
@@ -15,7 +15,7 @@ ip -6 route
 free -h
 top -n 1 -b -o RES
 rpm -qa | sort
-yum repolist -v
+{{ ansible_pkg_mgr }} repolist -v
 sudo os-collect-config --print
 which pcs &> /dev/null && sudo pcs status --full
 which pcs &> /dev/null && sudo pcs constraint show --full
@@ -27,9 +27,9 @@ find ~jenkins -iname tripleo-overcloud-passwords -execdir cat '{}' ';'
 sudo systemctl list-units --full --all
 
 
-if [ -e /home/{{ undercloud_user }}/stackrc ] ; then
+if [ -e {{ working_dir }}/stackrc ] ; then
 bash <<-EOF &>/var/log/postci.txt
-    source /home/{{ undercloud_user }}/stackrc
+    source {{ working_dir }}/stackrc
     openstack <<-EOC
     server list -f yaml
     workflow list -f yaml
@@ -53,5 +53,7 @@ EOC
     # NOTE(bnemec): openstack stack failures list only exists in Newton and above.
     # On older releases we still need to manually query the deployments.
     openstack stack failures list --long overcloud || for failed_deployment in \$(heat resource-list --nested-depth 5 overcloud | grep FAILED | grep 'StructuredDeployment ' | cut -d '|' -f3); do heat deployment-show \$failed_deployment; done;
+    # NOTE(emilien) "openstack overcloud failures" was introduced in Rocky
+    openstack overcloud failures || true
 EOF
 fi
